// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

error InvalidPrice();
error InvalidExpiry();
error InvalidPaymentToken();
error InvalidPayoutAddress();
error InvalidConditionEvaluator();
error InvalidEvaluatorMetadataHash();
error InvalidEvaluatorRegistrationFee(uint256 expectedFee, uint256 actualFee);
error InvalidConditionInputCount();
error PolicyConditionFailed(uint256 conditionIndex);
error InvalidIdentityRegistry();
error InvalidAgentId();
error AgentIdentityNotFound();
error InvalidRequiredBuyerUaid();
error PaymentFailed();
error NotPolicyProvider();
error NotDatasetProvider();
error PolicyNotFound();
error DatasetNotFound();
error PolicyInactive();
error PolicyExpired();
error InvalidPolicyHashes();
error InvalidDatasetHashes();
error InvalidModuleAddress();
error InvalidFeeRecipient();
error DatasetInactive();
error EvaluatorAlreadyRegistered();
error EvaluatorNotRegistered();
error EvaluatorInactive();
error EvaluatorRegistrationPayoutFailed();
error BuyerNotAllowlisted();
error NotPaymentModule();
error ReceiptNonTransferable();
error AlreadyHasReceipt();
error BuyerUaidRequired();
error BuyerUaidMismatch();
error BuyerDoesNotOwnRequiredAgent();
